/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00464a",
        "primary-container": "#006064",
        "on-primary": "#ffffff",
        "on-primary-container": "#8fd8dc",
        "primary-fixed": "#a6eff3",
        "primary-fixed-dim": "#8ad3d7",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#004f53",
        "secondary": "#735c00",
        "secondary-container": "#fed65b",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#241a00",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "tertiary": "#62330f",
        "tertiary-container": "#7e4924",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffbe95",
        "tertiary-fixed": "#ffdbc7",
        "surface": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "surface-tint": "#14696d",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#3f4949",
        "outline": "#6f7979",
        "outline-variant": "#bec8c9",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        serif: ["Noto Serif", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
      },
      boxShadow: {
        zen: "0 16px 32px 0 rgba(27,28,25,0.06)",
        float: "0 8px 24px 0 rgba(27,28,25,0.08)",
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeInUp: 'fadeInUp 0.2s ease',
      },
    },
  },
  plugins: [],
}

